name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'screenshots/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Detect repository type
        id: detect-type
        run: |
          if [ -f ".repository-type" ]; then
            REPO_TYPE=$(grep -oP 'repository:\s*\K\w+' .repository-type || echo "private")
          else
            REPO_TYPE="private"
          fi
          echo "REPO_TYPE=$REPO_TYPE" >> $GITHUB_ENV
          echo "Detected repository type: $REPO_TYPE"
      
      - name: Prepare documentation
        run: |
          # Create temp directory
          mkdir -p _site
          
          # Copy documentation files
          cp -r docs/* _site/
          
          # Copy screenshots for documentation
          if [ -d "screenshots" ]; then
            mkdir -p _site/screenshots
            cp -r screenshots/* _site/screenshots/
          fi
          
          # Create .nojekyll file to bypass Jekyll processing
          touch _site/.nojekyll
          
          # Create index.html
          cat > _site/index.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Inventory Management System Documentation</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
              }
              h1 {
                color: #2c3e50;
                border-bottom: 2px solid #eee;
                padding-bottom: 10px;
              }
              h2 {
                color: #3498db;
                margin-top: 30px;
              }
              a {
                color: #3498db;
                text-decoration: none;
              }
              a:hover {
                text-decoration: underline;
              }
              .header {
                text-align: center;
                margin-bottom: 30px;
              }
              .repo-type {
                display: inline-block;
                padding: 5px 10px;
                border-radius: 3px;
                color: white;
                font-weight: bold;
                margin-left: 10px;
              }
              .private {
                background-color: #e74c3c;
              }
              .public {
                background-color: #2ecc71;
              }
              .sandbox {
                background-color: #f39c12;
              }
              .documentation-list {
                background-color: #f8f9fa;
                border-radius: 5px;
                padding: 20px;
                margin-bottom: 20px;
              }
              .documentation-list ul {
                list-style-type: none;
                padding-left: 0;
              }
              .documentation-list li {
                margin-bottom: 10px;
                padding: 10px;
                border-bottom: 1px solid #eee;
              }
              .documentation-list li:last-child {
                border-bottom: none;
              }
              .footer {
                margin-top: 50px;
                text-align: center;
                font-size: 0.9em;
                color: #7f8c8d;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>Inventory Management System 
              <span class="repo-type $REPO_TYPE">${REPO_TYPE^^}</span>
              </h1>
              <p>Documentation and Resources</p>
            </div>
          
            <div class="documentation-list">
              <h2>Documentation</h2>
              <ul>
                <li><a href="REPOSITORY_STRUCTURE.md">Repository Structure</a></li>
                <li><a href="API.md">API Documentation</a></li>
                <li><a href="DATABASE.md">Database Schema</a></li>
                <li><a href="USER_GUIDE.md">User Guide</a></li>
              </ul>
            </div>
          
            <div class="documentation-list">
              <h2>Screenshots</h2>
              <div style="display: flex; flex-wrap: wrap; gap: 20px; justify-content: center;">
                <div>
                  <h3>Dashboard</h3>
                  <img src="screenshots/dashboard.png" alt="Dashboard Screenshot" style="max-width: 300px;">
                </div>
                <div>
                  <h3>Inventory</h3>
                  <img src="screenshots/inventory.png" alt="Inventory Screenshot" style="max-width: 300px;">
                </div>
                <div>
                  <h3>Transactions</h3>
                  <img src="screenshots/transactions.png" alt="Transactions Screenshot" style="max-width: 300px;">
                </div>
              </div>
            </div>
          
            <div class="footer">
              <p>Inventory Management System &copy; 2025</p>
              <p>Repository Type: <strong>${REPO_TYPE^^}</strong></p>
            </div>
          </body>
          </html>
          EOF
          
          # Create README
          cat > _site/README.md << EOF
          # Inventory Management System Documentation
          
          This repository contains documentation for the Inventory Management System ($REPO_TYPE version).
          
          - [Repository Structure](REPOSITORY_STRUCTURE.md)
          - [API Documentation](API.md)
          - [Database Schema](DATABASE.md)
          - [User Guide](USER_GUIDE.md)
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2